apiVersion: game.game.com/v1
kind: Game
metadata:
  labels:
    app.kubernetes.io/name: game
    app.kubernetes.io/managed-by: kustomize
  name: game-sample
spec:
  replicas: 1
  image: stanhoe/docker-2048:injected
  host: game.com