# permissions for end users to view games.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: game
    app.kubernetes.io/managed-by: kustomize
  name: game-viewer-role
rules:
- apiGroups:
  - game.game.com
  resources:
  - games
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - game.game.com
  resources:
  - games/status
  verbs:
  - get
